### PR TITLE
ci: shared jobs with msys2 windows build

### PR DESCRIPTION
**Pull request by antonbaliasnikov**

### CODE REVIEW

**Comment by antonbaliasnikov** [comment]
@hedgar2017 , @abinavpp , do you know what can cause the benchmark regressions? Is this expected?

**Review by hedgar2017 — CHANGES_REQUESTED** [review]
Hey @antonbaliasnikov, it looks like there are different commits of compiler-tester used in reference and candidate: https://github.com/matter-labs/era-solidity/actions/runs/11442884776/job/31835185943#step:4:1
Do you know why it might be happening?

**Comment by antonbaliasnikov** [comment]
> Hey @antonbaliasnikov, it looks like there are different commits of compiler-tester used in reference and candidate: https://github.com/matter-labs/era-solidity/actions/runs/11442884776/job/31835185943#step:4:1 Do you know why it might be happening?

@hedgar2017 , ah, I see that https://github.com/matter-labs/era-compiler-tester/releases/tag/era-solidity-test tag was created 2 weeks ago. Should we remove it?

**Comment by hedgar2017** [comment]
> > Hey @antonbaliasnikov, it looks like there are different commits of compiler-tester used in reference and candidate: https://github.com/matter-labs/era-solidity/actions/runs/11442884776/job/31835185943#step:4:1 Do you know why it might be happening?
> 
> 
> 
> @hedgar2017 , ah, I see that https://github.com/matter-labs/era-compiler-tester/releases/tag/era-solidity-test tag was created 2 weeks ago. Should we remove it?

Sure.
The tag is only used for candidate, isn't it?

**Review by hedgar2017 — APPROVED** [review]

**Comment by antonbaliasnikov** [comment]
> > > Hey @antonbaliasnikov, it looks like there are different commits of compiler-tester used in reference and candidate: https://github.com/matter-labs/era-solidity/actions/runs/11442884776/job/31835185943#step:4:1 Do you know why it might be happening?
> > 
> > 
> > @hedgar2017 , ah, I see that https://github.com/matter-labs/era-compiler-tester/releases/tag/era-solidity-test tag was created 2 weeks ago. Should we remove it?
> 
> Sure. The tag is only used for candidate, isn't it?

Right, and this caused the difference between `main` and this tag.

**Pull request merged**
