### PR TITLE
fix: the try-catch lowering hack for 0.8.25

### PR DESCRIPTION
**Pull request by abinavpp**
# What ❔
Fixes the try-catch lowering hack.

## Why ❔
CPR-1705

## Checklist

- [x] PR title corresponds to the body of PR (we generate changelog entries from PRs).
- [x] Tests for the changes have been added / updated.
- [x] Documentation comments have been added / updated.

### CODE REVIEW

**Review by hedgar2017 — CHANGES_REQUESTED** [review]
Thanks, LGTM!

Could you update the changelog? Assume it's a version 1.0.1

**Comment by abinavpp** [comment]
> Thanks, LGTM!
> 
> Could you update the changelog? Assume it's a version 1.0.1

Done.

**Review by hedgar2017 — APPROVED** [review]

**Comment by hedgar2017** [comment]
@antonbaliasnikov is there ZKSYNC_VERSION set for the reference build?

**Comment by antonbaliasnikov** [comment]
> @antonbaliasnikov is there ZKSYNC_VERSION set for the reference build?

Yeah, this was due to last second changes in `SOL_*`/`SOLC_*` variable renaming. I updated the `latest-ci` tag to take the reference case and restarted the workflow. Let's wait for the new results.

**Comment by antonbaliasnikov** [comment]
New results for the [reference](https://github.com/matter-labs/era-solidity/actions/runs/9275207851/job/25541190364), all looks good now.

**Review by hedgar2017 — CHANGES_REQUESTED** [review]
Let's merge when reference passes.

**Comment by antonbaliasnikov** [comment]
> Let's merge when reference passes.

The reference does not contain this patch, so it failed with:
```
E+M3B3 0.8.25    INVALID tests/solidity/simple/try_catch/nested_2.sol Failed to compile sources: `solc` errors found: ["InternalCompilerError: Assembly exception for bytecode\n\n"]
E+MzB3 0.8.25    INVALID tests/solidity/simple/try_catch/nested_2.sol Failed to compile sources: `solc` errors found: ["InternalCompilerError: Assembly exception for bytecode\n\n"]
```

**Comment by hedgar2017** [comment]
> > Let's merge when reference passes.
> 
> 
> 
> The reference does not contain this patch, so it failed with:
> 
> ```
> 
> E+M3B3 0.8.25    INVALID tests/solidity/simple/try_catch/nested_2.sol Failed to compile sources: `solc` errors found: ["InternalCompilerError: Assembly exception for bytecode\n\n"]
> 
> E+MzB3 0.8.25    INVALID tests/solidity/simple/try_catch/nested_2.sol Failed to compile sources: `solc` errors found: ["InternalCompilerError: Assembly exception for bytecode\n\n"]
> 
> ```

Please check DM in Slack!

**Comment by abinavpp** [comment]
> Let's merge when reference passes.

Reference is expected to fail right? The reference solc binary doesn't have this patch that would fix the compilation of try_catch/nested_2.sol, right?

**Comment by hedgar2017** [comment]
> > Let's merge when reference passes.
> 
> 
> 
> Reference is expected to fail right? The reference solc binary doesn't have this patch that would fix the compilation of try_catch/nested_2.sol, right?

Nope. Reference has always supposed to pass, as it contains neither the fix nor the reproducer to fail.

Its only purpose is to produce a benchmark for candidate to compare with.

**Comment by hedgar2017** [comment]
@antonbaliasnikov thanks. Let's have CI changes in one commit.

**Comment by hedgar2017** [comment]
@abinavpp after rebase, the changelog should go away and we'll end up with two commits: the fix and the CI.

**Pull request closed without merging**
